version: "3.7"

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    networks:
    # network references caddy needs to access
    # see the networks section for more details
      - ctfd
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/confi
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        reservations:
          memory: 500M    

volumes:
  caddy_data:
  caddy_config:

networks:
# add any app-specific networks that caddy needs access to
  ctfd:
    external:
      name: ctfd_default
      # default network for CTFd created by docker
